
CostCurtailment: 10000 #EUR/MWh

FuelPrice: 
  2017: 
    #GAS: 18.08
    LIG: 20.49
    WAT: 0
  2018:
    #GAS: 21.23
    LIG: 22.11
    WAT: 0

NoLoadCost: 25000

PermitPrice:
  2017: 7.64
  2018: 23.56

ReserveParticipation:
- 'COMC'
- 'HDR'



